### ISSUE TITLE
AttributeError: 'Agent' object has no attribute 'q_gru_keep_prob'

### ISSUE THREAD

**Issue by SdxHex** [samre12/deep-trading-agent#14]
Problems with Python 3.6 - Unable to get past this point

`2018-05-21 08:58:16.038248: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-05-21 08:58:16.278040: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 1050 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.4425
pciBusID: 0000:02:00.0
totalMemory: 4.00GiB freeMemory: 3.29GiB
2018-05-21 08:58:16.278375: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1435] Adding visible gpu devices: 0
2018-05-21 08:58:16.779930: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-05-21 08:58:16.780127: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:929]      0 
2018-05-21 08:58:16.780253: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:942] 0:   N 
2018-05-21 08:58:16.780467: I T:\src\github\tensorflow\tensorflow\core\common_runtime\gpu\gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3025 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO: Making new env: UnRealizedPnLEnv-v0
Traceback (most recent call last):
  File "D:/deep-trading-agent-dev/code/main.py", line 44, in <module>
    main(vars(args)['file_path'])
  File "D:/deep-trading-agent-dev/code/main.py", line 34, in main
    agent = Agent(sess, logger, config, env)
  File "D:\deep-trading-agent-dev\code\model\agent.py", line 252, in __init__
    self.build_dqn(params)
  File "D:\deep-trading-agent-dev\code\model\agent.py", line 448, in build_dqn
    print (self.q_gru_keep_prob)
AttributeError: 'Agent' object has no attribute 'q_gru_keep_prob'`

**Comment by samre12** [comment]
@SdxHex the project is developed taking python2 as the development environment. Converting to python3 code base is still under progress.
